fix: move to workspace before clean
Running `make distclean` gives the following error:
Error: The current directory does not appear to be a valid workspace.

The workspace is cloned to `c200` directory[0]. Running command
`./edk2_docker edkrepo clean` in c200 directory to fix the error.

[0]: https://github.com/radxa/c200-bootupd/blob/42e88ed13950710c034400067d599d8bbd9cab00/Makefile#L53